from pathlib import Path


def read(p): return Path(p).read_text(encoding='utf-8')
def write(p,s): Path(p).write_text(s,encoding='utf-8')
def one(s, old, new, label):
    c=s.count(old)
    if c != 1: raise RuntimeError(f'{label}: expected 1 match, got {c}')
    return s.replace(old,new,1)

p1=read('src/engine_impl/part1.rs')
p2=read('src/engine_impl/part2.rs')
p3=read('src/engine_impl/part3.rs')
p4=read('src/engine_impl/part4.rs')

p1=one(p1,'use std::io::{BufWriter, Read, Write};','use std::io::{BufWriter, Write};\n#[cfg(not(windows))]\nuse std::io::Read;','read import')
p1=one(p1,'use std::path::{Path, PathBuf};','use std::path::{Component, Path, PathBuf};','component import')

anchor='''fn dest_inside_source(src: &Path, dst: &Path) -> bool {\n    if dst.starts_with(src) { return true; }\n    match (src.canonicalize(), dst.canonicalize()) {\n        (Ok(s), Ok(d)) => d == s || d.starts_with(&s),\n        _ => false,\n    }\n}\n'''
insert=anchor+'''\n#[cfg(windows)]\nfn runtime_is_reparse(meta: &fs::Metadata) -> bool {\n    use std::os::windows::fs::MetadataExt;\n    meta.file_attributes() & 0x0000_0400 != 0\n}\n\n#[cfg(not(windows))]\nfn runtime_is_reparse(_: &fs::Metadata) -> bool { false }\n\nfn validate_runtime_destination_path(root: &Path, rel: &Path) -> Result<(), String> {\n    let root_meta = fs::symlink_metadata(root)\n        .map_err(|e| format!("No se pudo inspeccionar destino {}: {e}", root.display()))?;\n    if !root_meta.is_dir() || root_meta.file_type().is_symlink() || runtime_is_reparse(&root_meta) {\n        return Err(format!("Destino inseguro o reemplazado durante la copia: {}", root.display()));\n    }\n    let components: Vec<Component<'_>> = rel.components().collect();\n    if components.is_empty() { return Err("Ruta relativa vacía".into()); }\n    let mut current = root.to_path_buf();\n    for (idx, component) in components.iter().enumerate() {\n        let Component::Normal(name) = component else {\n            return Err(format!("Ruta relativa insegura: {}", rel.display()));\n        };\n        current.push(name);\n        match fs::symlink_metadata(&current) {\n            Ok(meta) => {\n                if meta.file_type().is_symlink() || runtime_is_reparse(&meta) {\n                    return Err(format!("La ruta de destino cambió a symlink/junction/reparse point durante la copia: {}", current.display()));\n                }\n                let last = idx + 1 == components.len();\n                if !last && !meta.is_dir() {\n                    return Err(format!("Componente de destino ya no es carpeta: {}", current.display()));\n                }\n                if last && meta.is_dir() {\n                    return Err(format!("El destino final cambió a carpeta: {}", current.display()));\n                }\n            }\n            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}\n            Err(e) => return Err(format!("No se pudo inspeccionar {}: {e}", current.display())),\n        }\n    }\n    Ok(())\n}\n'''
p1=one(p1,anchor,insert,'runtime path helper')

p1=one(p1,'struct StateJournal {','''fn sync_log_data(file: &File, state: &JobState, control: &DestControl, label: &str) -> Result<(), String> {\n    #[cfg(windows)]\n    {\n        let clone = file.try_clone().map_err(|e| format!("{label} sync clone: {e}"))?;\n        crate::windows_io::sync_file_cancelable(clone, || {\n            state.cancel.load(Ordering::Acquire) || !control.alive.load(Ordering::Acquire)\n        }).map_err(|e| {\n            if e.kind() == std::io::ErrorKind::Interrupted && state.cancel.load(Ordering::Acquire) {\n                "Cancelado".to_owned()\n            } else if e.kind() == std::io::ErrorKind::Interrupted && !control.alive.load(Ordering::Acquire) {\n                format!("{label} interrumpido porque el destino dejó de responder")\n            } else {\n                format!("{label} sync: {e}")\n            }\n        })\n    }\n    #[cfg(not(windows))]\n    {\n        file.sync_data().map_err(|e| format!("{label} sync: {e}"))\n    }\n}\n\nstruct StateJournal {''','log sync helper')

old='''    fn checkpoint(&mut self) -> Result<(), String> {\n        if self.pending == 0 { return Ok(()); }\n        self.writer.flush().map_err(|e| format!("state flush: {e}"))?;\n        self.writer.get_ref().sync_data().map_err(|e| format!("state sync: {e}"))?;\n        self.pending = 0;\n        self.last_sync = Instant::now();\n        Ok(())\n    }\n\n    fn finish(&mut self) -> Result<(), String> { self.checkpoint() }\n'''
new='''    fn checkpoint(&mut self, state: &JobState, control: &DestControl) -> Result<(), String> {\n        if self.pending == 0 { return Ok(()); }\n        self.writer.flush().map_err(|e| format!("state flush: {e}"))?;\n        sync_log_data(self.writer.get_ref(), state, control, "state")?;\n        self.pending = 0;\n        self.last_sync = Instant::now();\n        Ok(())\n    }\n\n    fn finish(&mut self, state: &JobState, control: &DestControl) -> Result<(), String> {\n        self.checkpoint(state, control)\n    }\n'''
p1=one(p1,old,new,'journal sync')

old='''    fn finish(&mut self) -> Result<(), String> {\n        if !self.dirty { return Ok(()); }\n        self.writer.flush().map_err(|e| format!("manifest flush: {e}"))?;\n        self.writer.get_ref().sync_data().map_err(|e| format!("manifest sync: {e}"))?;\n        self.dirty = false;\n        Ok(())\n    }\n}\n\nimpl Drop for ManifestWriter {\n    fn drop(&mut self) { let _ = self.finish(); }\n}\n'''
new='''    fn finish(&mut self, state: &JobState, control: &DestControl) -> Result<(), String> {\n        if !self.dirty { return Ok(()); }\n        self.writer.flush().map_err(|e| format!("manifest flush: {e}"))?;\n        sync_log_data(self.writer.get_ref(), state, control, "manifest")?;\n        self.dirty = false;\n        Ok(())\n    }\n}\n\nimpl Drop for ManifestWriter {\n    fn drop(&mut self) { let _ = self.writer.flush(); }\n}\n'''
p1=one(p1,old,new,'manifest sync')

old='''fn checkpoint_logs(manifest: &mut ManifestWriter, journal: &mut StateJournal) -> Result<(), String> {\n    manifest.finish()?;\n    journal.checkpoint()\n}\n\nfn finish_logs(manifest: &mut ManifestWriter, journal: &mut StateJournal) -> Result<(), String> {\n    manifest.finish()?;\n    journal.finish()\n}\n'''
new='''fn checkpoint_logs(manifest: &mut ManifestWriter, journal: &mut StateJournal, state: &JobState, control: &DestControl) -> Result<(), String> {\n    manifest.finish(state, control)?;\n    journal.checkpoint(state, control)\n}\n\nfn finish_logs(manifest: &mut ManifestWriter, journal: &mut StateJournal, state: &JobState, control: &DestControl) -> Result<(), String> {\n    manifest.finish(state, control)?;\n    journal.finish(state, control)\n}\n'''
p1=one(p1,old,new,'log signatures')

old='''fn hash_file_with_buffer(\n    path: &Path,\n    buf: &mut [u8],\n    state: Option<&JobState>,\n) -> Result<blake3::Hash, String> {\n    let mut f = File::open(path).map_err(|e| format!("verificar: {e}"))?;\n    let mut h = blake3::Hasher::new();\n    loop {\n        if let Some(s) = state {\n            if !wait_pause(s) { return Err("Cancelado".into()); }\n        }\n        let n = f.read(buf).map_err(|e| format!("verificar: {e}"))?;\n        if n == 0 { break; }\n        h.update(&buf[..n]);\n    }\n    Ok(h.finalize())\n}\n'''
new='''fn hash_file_with_buffer(\n    path: &Path,\n    buf: &mut [u8],\n    state: Option<&JobState>,\n) -> Result<blake3::Hash, String> {\n    hash_file_with_buffer_control(path, buf, state, None)\n}\n\nfn hash_file_with_buffer_control(\n    path: &Path,\n    buf: &mut [u8],\n    state: Option<&JobState>,\n    control: Option<&DestControl>,\n) -> Result<blake3::Hash, String> {\n    #[cfg(windows)]\n    {\n        crate::windows_io::hash_file_cancelable(path, buf.len(), || {\n            state.is_some_and(|s| s.cancel.load(Ordering::Acquire))\n                || control.is_some_and(|c| !c.alive.load(Ordering::Acquire))\n        }).map_err(|e| {\n            if e.kind() == std::io::ErrorKind::Interrupted && state.is_some_and(|s| s.cancel.load(Ordering::Acquire)) {\n                "Cancelado".to_owned()\n            } else if e.kind() == std::io::ErrorKind::Interrupted && control.is_some_and(|c| !c.alive.load(Ordering::Acquire)) {\n                "Destino detenido".to_owned()\n            } else {\n                format!("verificar: {e}")\n            }\n        })\n    }\n    #[cfg(not(windows))]\n    {\n        let mut f = File::open(path).map_err(|e| format!("verificar: {e}"))?;\n        let mut h = blake3::Hasher::new();\n        loop {\n            if let Some(s) = state { if !wait_pause(s) { return Err("Cancelado".into()); } }\n            if control.is_some_and(|c| !c.alive.load(Ordering::Acquire)) { return Err("Destino detenido".into()); }\n            let n = f.read(buf).map_err(|e| format!("verificar: {e}"))?;\n            if n == 0 { break; }\n            h.update(&buf[..n]);\n        }\n        Ok(h.finalize())\n    }\n}\n'''
p2=one(p2,old,new,'worker hash')

p2=one(p2,'let verify_result = hash_file_with_buffer(&tmp, buf, Some(&state));','let verify_result = hash_file_with_buffer_control(&tmp, buf, Some(&state), Some(&control));','verify call')

p2=one(p2,'''                let dst = dest.join(&info.rel);\n                cleanup_part(&dest, &dst);\n''','''                let dst = dest.join(&info.rel);\n                if let Err(e) = validate_runtime_destination_path(&dest, &info.rel) {\n                    record_file_error(&state, slot, e);\n                    if !opts.keep_going { control.alive.store(false, Ordering::Release); break; }\n                    continue;\n                }\n                cleanup_part(&dest, &dst);\n''','begin runtime validation')

p2=one(p2,'''                    if let Err(e) = sync_result {\n                        cur.file.take();\n                        cleanup_part(&dest, &dst);\n                        rollback_write_progress(&state, slot, cur.copied, &mut effective_written, start);\n                        if e != "Cancelado" {\n''','''                    if let Err(e) = sync_result {\n                        cur.file.take();\n                        cleanup_part(&dest, &dst);\n                        rollback_write_progress(&state, slot, cur.copied, &mut effective_written, start);\n                        if !control.alive.load(Ordering::Acquire) { break; }\n                        if e != "Cancelado" {\n''','sync stalled exit')

p2=one(p2,'''                        Err(e) => {\n                            cleanup_part(&dest, &dst);\n                            rollback_write_progress(&state, slot, cur.copied, &mut effective_written, start);\n                            if e == "Cancelado" {\n''','''                        Err(e) => {\n                            cleanup_part(&dest, &dst);\n                            rollback_write_progress(&state, slot, cur.copied, &mut effective_written, start);\n                            if !control.alive.load(Ordering::Acquire) { break; }\n                            if e == "Cancelado" {\n''','verify stalled exit')

p2=one(p2,'''                control.enter_operation(OperationPhase::Commit);\n                let commit_result = retry_commit(&state, slot, || commit_part_fast(&dest, &tmp, &dst));\n''','''                if let Err(e) = validate_runtime_destination_path(&dest, &cur.info.rel) {\n                    cleanup_part(&dest, &dst);\n                    rollback_write_progress(&state, slot, cur.copied, &mut effective_written, start);\n                    record_file_error(&state, slot, e);\n                    if !opts.keep_going { control.alive.store(false, Ordering::Release); break; }\n                    continue;\n                }\n                control.enter_operation(OperationPhase::Commit);\n                let commit_result = retry_commit(&state, slot, || commit_part_fast(&dest, &tmp, &dst));\n''','commit runtime validation')

old='''                if journal.needs_checkpoint() {\n                    if let Err(e) = checkpoint_logs(&mut manifest, &mut journal) {\n                        record_file_error(&state, slot, e);\n                        if !opts.keep_going {\n                            control.alive.store(false, Ordering::Release);\n                            break;\n                        }\n                        continue;\n                    }\n                }\n'''
new='''                if journal.needs_checkpoint() {\n                    control.enter_operation(OperationPhase::Sync);\n                    let checkpoint_result = checkpoint_logs(&mut manifest, &mut journal, &state, &control);\n                    control.enter_operation(OperationPhase::Write);\n                    if let Err(e) = checkpoint_result {\n                        if !control.alive.load(Ordering::Acquire) { break; }\n                        record_file_error(&state, slot, e);\n                        if !opts.keep_going { control.alive.store(false, Ordering::Release); break; }\n                        continue;\n                    }\n                }\n'''
p2=one(p2,old,new,'checkpoint')

p2=one(p2,'    if let Err(e) = finish_logs(&mut manifest, &mut journal) {','''    control.enter_operation(OperationPhase::Sync);\n    let finish_result = finish_logs(&mut manifest, &mut journal, &state, &control);\n    control.enter_operation(OperationPhase::Write);\n    if let Err(e) = finish_result {''','finish logs')

old='''    if state.cancel.load(Ordering::Relaxed) {\n        set_phase(&state, slot, DestPhase::Cancelled, Some("Cancelado".into()));\n        return;\n    }\n\n    let errs = state.dests.lock().unwrap()[slot].files_err;\n    if !control.alive.load(Ordering::Acquire) {\n        set_phase(&state, slot, DestPhase::Failed, None);\n    } else if errs == 0 {\n        set_phase(&state, slot, DestPhase::Done, None);\n    } else {\n        set_phase(&state, slot, DestPhase::Done, Some(format!("Terminado con {errs} error(es).")));\n    }\n}\n'''
new='''    if state.cancel.load(Ordering::Relaxed) {\n        set_phase(&state, slot, DestPhase::Cancelled, Some("Cancelado".into()));\n        control.alive.store(false, Ordering::Release);\n        control.note_progress();\n        return;\n    }\n\n    let errs = state.dests.lock().unwrap()[slot].files_err;\n    if !control.alive.load(Ordering::Acquire) {\n        set_phase(&state, slot, DestPhase::Failed, None);\n    } else if errs == 0 {\n        set_phase(&state, slot, DestPhase::Done, None);\n    } else {\n        set_phase(&state, slot, DestPhase::Done, Some(format!("Terminado con {errs} error(es).")));\n    }\n    control.alive.store(false, Ordering::Release);\n    control.note_progress();\n}\n'''
p2=one(p2,old,new,'worker final lifecycle')

p3=one(p3,'fn mark_skipped_all(state: &JobState, info: &FileInfo, mask: &[bool]) {','''fn watch_workers_after_input_closed(controls: &[Arc<DestControl>], state: &JobState, pending: &mut PendingQueues) {\n    let mut seen: Vec<u64> = controls.iter().map(|c| c.progress_seq()).collect();\n    let mut last: Vec<Instant> = controls.iter().map(|_| Instant::now()).collect();\n    while controls.iter().any(|c| c.alive.load(Ordering::Acquire)) {\n        if state.cancel.load(Ordering::Acquire) {\n            for c in controls { c.alive.store(false, Ordering::Release); c.note_progress(); }\n        }\n        for slot in 0..controls.len() {\n            if !controls[slot].alive.load(Ordering::Acquire) { continue; }\n            let seq=controls[slot].progress_seq();\n            if seq != seen[slot] { seen[slot]=seq; last[slot]=Instant::now(); }\n            if controls[slot].stall_timed_out(last[slot]) {\n                fail_stalled_destination(slot, pending, controls, state);\n            }\n        }\n        thread::sleep(Duration::from_millis(20));\n    }\n}\n\nfn mark_skipped_all(state: &JobState, info: &FileInfo, mask: &[bool]) {''','tail watcher')
p3=one(p3,'        drop(senders);\n','        drop(senders);\n        watch_workers_after_input_closed(&controls, &state, &mut pending);\n','tail watcher call')

p4=one(p4,'    #[test]\n    fn stall_thresholds_allow_slow_storage() {','''    #[test]\n    fn tail_watchdog_marks_stalled_final_operation_failed() {\n        let root = temp_dir("tail-watchdog");\n        let state = worker_state(&root, 0);\n        let control = Arc::new(DestControl::new());\n        *control.operation.lock().unwrap() = (OperationPhase::Verify, Instant::now() - LONG_OP_THRESHOLD - Duration::from_secs(1));\n        let controls = vec![Arc::clone(&control)];\n        let mut pending: PendingQueues = vec![std::collections::VecDeque::new()];\n        watch_workers_after_input_closed(&controls, &state, &mut pending);\n        assert!(!control.alive.load(Ordering::Acquire));\n        let snap=state.snapshot();\n        assert_eq!(snap[0].phase, DestPhase::Failed);\n        assert!(snap[0].error.as_deref().is_some_and(|e| e.contains("Destino atascado")));\n        let _=fs::remove_dir_all(root);\n    }\n\n    #[test]\n    fn runtime_destination_validation_rejects_directory_at_file_path() {\n        let root=temp_dir("runtime-path");\n        fs::create_dir_all(root.join("a.bin")).unwrap();\n        assert!(validate_runtime_destination_path(&root, Path::new("a.bin")).is_err());\n        let _=fs::remove_dir_all(root);\n    }\n\n    #[test]\n    fn stall_thresholds_allow_slow_storage() {''','tests')

write('src/engine_impl/part1.rs',p1)
write('src/engine_impl/part2.rs',p2)
write('src/engine_impl/part3.rs',p3)
write('src/engine_impl/part4.rs',p4)
