from pathlib import Path


def replace_one(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected 1 match, got {count}")
    return text.replace(old, new, 1)

p1 = Path('src/app/part1.rs')
p4 = Path('src/app/part4.rs')
p5 = Path('src/app/part5.rs')

part1 = p1.read_text(encoding='utf-8')
part4 = p4.read_text(encoding='utf-8')
part5 = p5.read_text(encoding='utf-8')

needle = '''fn progress_fraction(written: u64, total: u64, phase: DestPhase) -> f32 {\n    if total == 0 {\n        return if phase == DestPhase::Done { 1.0_f32 } else { 0.0_f32 };\n    }\n    (written as f64 / total as f64).clamp(0.0, 1.0) as f32\n}\n'''
addition = needle + '''\nfn source_layout_stacked(available_width: f32) -> bool {\n    available_width < 720.0\n}\n\nfn start_disabled_reason(\n    source: &str,\n    destination_count: usize,\n    path_error_count: usize,\n) -> Option<&'static str> {\n    if source.trim().is_empty() {\n        Some("Selecciona una carpeta de origen")\n    } else if destination_count == 0 {\n        Some("Agrega al menos un destino")\n    } else if path_error_count > 0 {\n        Some("Corrige los problemas de ruta antes de iniciar")\n    } else {\n        None\n    }\n}\n\nfn contains_mojibake(text: &str) -> bool {\n    [\n        "\\u{FFFD}",\n        "\\u{00C3}",\n        "\\u{00C2}",\n        "\\u{00E2}\\u{20AC}",\n        "\\u{00F0}\\u{0178}",\n    ]\n    .iter()\n    .any(|marker| text.contains(marker))\n}\n'''
part1 = replace_one(part1, needle, addition, 'responsive and text sanitation helpers')

old_source = '''            ui.horizontal(|ui| {\n                ui.label(\n                    RichText::new("ORIGEN")\n                        .size(10.5)\n                        .strong()\n                        .color(Theme::muted(self.use_light_theme)),\n                );\n                let button_width = 88.0;\n                let label_width = 54.0;\n                let field_width =\n                    (ui.available_width() - button_width - label_width - SPACING_SM).max(150.0);\n                ui.add_enabled_ui(!busy, |ui| {\n                    ui.add_sized(\n                        [field_width, 28.0],\n                        egui::TextEdit::singleline(&mut self.source)\n                            .hint_text("Carpeta que quieres copiar"),\n                    );\n                    if ui\n                        .add_sized([button_width, 28.0], egui::Button::new("Examinar"))\n                        .on_hover_text("Seleccionar carpeta de origen")\n                        .clicked()\n                    {\n                        if let Some(path) = self.pick_source_dir() {\n                            self.source = path;\n                        }\n                    }\n                });\n            });\n'''
new_source = '''            let stacked_source = source_layout_stacked(ui.available_width());\n            if stacked_source {\n                ui.vertical(|ui| {\n                    ui.label(\n                        RichText::new("ORIGEN")\n                            .size(10.5)\n                            .strong()\n                            .color(Theme::muted(self.use_light_theme)),\n                    );\n                    ui.add_enabled_ui(!busy, |ui| {\n                        let button_width = 88.0;\n                        let field_width = (ui.available_width() - button_width - SPACING_SM).max(150.0);\n                        ui.horizontal(|ui| {\n                            ui.add_sized(\n                                [field_width, 28.0],\n                                egui::TextEdit::singleline(&mut self.source)\n                                    .hint_text("Carpeta que quieres copiar"),\n                            );\n                            if ui\n                                .add_sized([button_width, 28.0], egui::Button::new("Examinar"))\n                                .on_hover_text("Seleccionar carpeta de origen")\n                                .clicked()\n                            {\n                                if let Some(path) = self.pick_source_dir() {\n                                    self.source = path;\n                                }\n                            }\n                        });\n                    });\n                });\n            } else {\n                ui.horizontal(|ui| {\n                    ui.label(\n                        RichText::new("ORIGEN")\n                            .size(10.5)\n                            .strong()\n                            .color(Theme::muted(self.use_light_theme)),\n                    );\n                    let button_width = 88.0;\n                    let label_width = 54.0;\n                    let field_width =\n                        (ui.available_width() - button_width - label_width - SPACING_SM).max(150.0);\n                    ui.add_enabled_ui(!busy, |ui| {\n                        ui.add_sized(\n                            [field_width, 28.0],\n                            egui::TextEdit::singleline(&mut self.source)\n                                .hint_text("Carpeta que quieres copiar"),\n                        );\n                        if ui\n                            .add_sized([button_width, 28.0], egui::Button::new("Examinar"))\n                            .on_hover_text("Seleccionar carpeta de origen")\n                            .clicked()\n                        {\n                            if let Some(path) = self.pick_source_dir() {\n                                self.source = path;\n                            }\n                        }\n                    });\n                });\n            }\n'''
part4 = replace_one(part4, old_source, new_source, 'adaptive source row')

old_ready = '''        let ready_to_start = !self.source.trim().is_empty()\n            && !self.dests.is_empty()\n            && path_error_count == 0;\n'''
new_ready = '''        let start_disabled =\n            start_disabled_reason(&self.source, self.dests.len(), path_error_count);\n        let ready_to_start = start_disabled.is_none();\n'''
part4 = replace_one(part4, old_ready, new_ready, 'start readiness explanation')

old_button = '''                        if ui\n                            .add_enabled(ready_to_start, button)\n                            .on_hover_text("Iniciar copia a todos los destinos")\n                            .clicked()\n'''
new_button = '''                        let start_hint = start_disabled\n                            .unwrap_or("Iniciar copia a todos los destinos");\n                        if ui\n                            .add_enabled(ready_to_start, button)\n                            .on_hover_text(start_hint)\n                            .clicked()\n'''
part4 = replace_one(part4, old_button, new_button, 'disabled start reason tooltip')

needle_test = '''    #[test]\n    fn compact_path_preserves_both_ends() {\n'''
new_tests = '''    #[test]\n    fn source_layout_stacks_at_narrow_widths() {\n        assert!(source_layout_stacked(680.0));\n        assert!(source_layout_stacked(719.0));\n        assert!(!source_layout_stacked(720.0));\n        assert!(!source_layout_stacked(960.0));\n    }\n\n    #[test]\n    fn disabled_start_always_has_a_specific_reason() {\n        assert_eq!(\n            start_disabled_reason("", 0, 0),\n            Some("Selecciona una carpeta de origen")\n        );\n        assert_eq!(\n            start_disabled_reason(r"C:\\Origen", 0, 0),\n            Some("Agrega al menos un destino")\n        );\n        assert_eq!(\n            start_disabled_reason(r"C:\\Origen", 1, 2),\n            Some("Corrige los problemas de ruta antes de iniciar")\n        );\n        assert_eq!(start_disabled_reason(r"C:\\Origen", 1, 0), None);\n    }\n\n    #[test]\n    fn unicode_paths_survive_display_and_compaction() {\n        let path = r"C:\\Música\\Niño\\日本語\\Документы\\archivo-especial.txt";\n        let compact = compact_path(path, 28);\n        assert!(compact.starts_with("C:"));\n        assert!(compact.ends_with("especial.txt"));\n        assert!(compact.contains('…'));\n        assert!(!compact.contains('�'));\n\n        let extended = r"\\\\?\\C:\\Música\\Niño\\日本語";\n        assert_eq!(display_path(extended), r"C:\\Música\\Niño\\日本語");\n    }\n\n    #[test]\n    fn ui_sources_do_not_contain_common_mojibake_sequences() {\n        for source in [\n            include_str!("part1.rs"),\n            include_str!("part2.rs"),\n            include_str!("part3.rs"),\n            include_str!("part4.rs"),\n        ] {\n            assert!(!contains_mojibake(source));\n        }\n    }\n\n''' + needle_test
part5 = replace_one(part5, needle_test, new_tests, 'unicode responsive regression tests')

p1.write_text(part1, encoding='utf-8')
p4.write_text(part4, encoding='utf-8')
p5.write_text(part5, encoding='utf-8')
