use crate::config::{load_settings, save_settings, AppSettings, ThemePreference};
use crate::engine::{format_bps, start_job, CopyOpts, DestPhase, JobState};
use eframe::egui::{self, Color32, RichText};
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};
use std::path::PathBuf;
use std::sync::atomic::Ordering;
use std::sync::{mpsc, Arc};
use std::thread::{self, JoinHandle};
use std::time::{Duration, Instant};

type StartResult = Result<(Arc<JobState>, Vec<JoinHandle<()>>), String>;
const XS:f32=4.0; const SM:f32=8.0; const MD:f32=12.0; const LG:f32=18.0;
const RUNNING_REPAINT:Duration=Duration::from_millis(200); const PAUSED_REPAINT:Duration=Duration::from_millis(500); const STARTING_REPAINT:Duration=Duration::from_millis(80); const ERROR_FLASH:Duration=Duration::from_secs(5); const THEME_CHECK_INTERVAL:Duration=Duration::from_secs(30); const PATH_CHECK_INTERVAL:Duration=Duration::from_secs(2); const SPEED_DECAY_GRACE_SECS:f64=0.5; const SPEED_DECAY_TAU_SECS:f64=2.0;
#[cfg(windows)] mod system_theme { use std::ffi::c_void; type HKey=*mut c_void; const HKEY_CURRENT_USER:HKey=0x8000_0001usize as HKey; const KEY_READ:u32=0x0002_0019; const REG_DWORD:u32=4; #[link(name="advapi32")] extern "system" { #[link_name="RegOpenKeyExW"] fn reg_open_key_ex_w(hkey:HKey,sub_key:*const u16,options:u32,desired:u32,result:*mut HKey)->i32; #[link_name="RegQueryValueExW"] fn reg_query_value_ex_w(hkey:HKey,value_name:*const u16,reserved:*mut u32,value_type:*mut u32,data:*mut u8,data_len:*mut u32)->i32; #[link_name="RegCloseKey"] fn reg_close_key(hkey:HKey)->i32; } pub fn is_light()->bool { let path:Vec<u16>="Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize".encode_utf16().chain(std::iter::once(0)).collect(); let name:Vec<u16>="AppsUseLightTheme".encode_utf16().chain(std::iter::once(0)).collect(); let mut key:HKey=std::ptr::null_mut(); if unsafe{reg_open_key_ex_w(HKEY_CURRENT_USER,path.as_ptr(),0,KEY_READ,&mut key)}!=0||key.is_null(){return false;} let mut ty=0u32;let mut value=0u32;let mut len=4u32;let ok=unsafe{reg_query_value_ex_w(key,name.as_ptr(),std::ptr::null_mut(),&mut ty,(&mut value as *mut u32).cast::<u8>(),&mut len)};unsafe{reg_close_key(key);} ok==0&&ty==REG_DWORD&&len==4&&value==1 } }
#[cfg(windows)] fn detect_system_theme()->bool{system_theme::is_light()} #[cfg(not(windows))] fn detect_system_theme()->bool{false} fn resolve_theme(p:ThemePreference)->bool{match p{ThemePreference::System=>detect_system_theme(),ThemePreference::Light=>true,ThemePreference::Dark=>false}}
#[cfg(windows)] fn setup_fonts(ctx:&egui::Context){let win=std::env::var_os("WINDIR").unwrap_or_else(||"C:\\Windows".into());let Ok(bytes)=std::fs::read(PathBuf::from(win).join("Fonts").join("segoeui.ttf"))else{return;};let mut fonts=egui::FontDefinitions::default();fonts.font_data.insert("segoe_ui".into(),egui::FontData::from_owned(bytes));if let Some(f)=fonts.families.get_mut(&egui::FontFamily::Proportional){f.insert(0,"segoe_ui".into());}ctx.set_fonts(fonts);} #[cfg(not(windows))] fn setup_fonts(_:&egui::Context){}
struct Theme; impl Theme{fn accent(l:bool)->Color32{if l{Color32::from_rgb(0,112,200)}else{Color32::from_rgb(86,200,255)}}fn success(l:bool)->Color32{if l{Color32::from_rgb(18,128,74)}else{Color32::from_rgb(92,210,145)}}fn warning(l:bool)->Color32{if l{Color32::from_rgb(170,96,0)}else{Color32::from_rgb(255,190,64)}}fn error(l:bool)->Color32{if l{Color32::from_rgb(196,43,28)}else{Color32::from_rgb(255,135,145)}}fn verify(l:bool)->Color32{if l{Color32::from_rgb(111,66,193)}else{Color32::from_rgb(190,155,255)}}fn muted(l:bool)->Color32{if l{Color32::from_gray(96)}else{Color32::from_gray(168)}}fn text(l:bool)->Color32{if l{Color32::from_gray(24)}else{Color32::from_gray(244)}}fn panel(l:bool)->Color32{if l{Color32::from_rgb(250,251,253)}else{Color32::from_rgb(29,30,33)}}fn card(l:bool)->Color32{if l{Color32::WHITE}else{Color32::from_rgb(36,38,42)}}fn selected(l:bool)->Color32{if l{Color32::from_rgb(231,245,255)}else{Color32::from_rgb(24,52,70)}}fn border(l:bool)->Color32{if l{Color32::from_rgb(216,221,228)}else{Color32::from_rgb(62,66,73)}}}
fn apply_theme(ctx:&egui::Context,light:bool){let mut v=if light{egui::Visuals::light()}else{egui::Visuals::dark()};v.panel_fill=Theme::panel(light);v.window_fill=Theme::panel(light);v.extreme_bg_color=Theme::card(light);v.widgets.noninteractive.bg_fill=Theme::panel(light);v.widgets.inactive.bg_fill=Theme::card(light);v.widgets.hovered.bg_stroke=egui::Stroke::new(1.0,Theme::accent(light));v.selection.bg_fill=Theme::accent(light);v.override_text_color=Some(Theme::text(light));ctx.set_visuals(v);ctx.style_mut(|s|{s.spacing.item_spacing=egui::vec2(SM,7.0);s.spacing.button_padding=egui::vec2(12.0,7.0);s.visuals.window_rounding=egui::Rounding::same(10.0);});}
fn card_frame(light:bool)->egui::Frame{egui::Frame::none().fill(Theme::card(light)).stroke(egui::Stroke::new(1.0,Theme::border(light))).rounding(egui::Rounding::same(8.0)).inner_margin(egui::Margin::symmetric(14.0,12.0))}
fn format_bytes(b:u64)->String{const K:f64=1024.0;const M:f64=K*1024.0;const G:f64=M*1024.0;let x=b as f64;if x>=G{format!("{:.2} GiB",x/G)}else if x>=M{format!("{:.1} MiB",x/M)}else if x>=K{format!("{:.1} KiB",x/K)}else{format!("{b} B")}}
fn count_label(n:u64,s:&str,p:&str)->String{format!("{n} {}",if n==1{s}else{p})} fn format_duration(secs:f64)->String{if !secs.is_finite()||secs<=0.0{return "—".into();}let t=secs.round()as u64;let h=t/3600;let m=(t%3600)/60;let s=t%60;if h>0{format!("{h:02}:{m:02}:{s:02}")}else{format!("{m:02}:{s:02}")}} fn shown_bps(b:f64,last:Instant)->f64{let idle=last.elapsed().as_secs_f64();if idle<=SPEED_DECAY_GRACE_SECS{b}else{b*(-(idle-SPEED_DECAY_GRACE_SECS)/SPEED_DECAY_TAU_SECS).exp()}}
fn compact_path(path:&str,max:usize)->String{let c:Vec<char>=path.chars().collect();if c.len()<=max||max<12{return path.into();}let h=(max*2)/5;let t=max.saturating_sub(h+1);format!("{}…{}",c[..h].iter().collect::<String>(),c[c.len()-t..].iter().collect::<String>())}
fn phase_label(p:DestPhase,errs:u64,l:bool,paused:bool)->(&'static str,Color32){if paused&&matches!(p,DestPhase::Copying|DestPhase::Verifying){return("PAUSADO",Theme::warning(l));}match p{DestPhase::Idle=>("EN ESPERA",Theme::muted(l)),DestPhase::Copying=>("COPIANDO",Theme::accent(l)),DestPhase::Verifying=>("VERIFICANDO INTEGRIDAD",Theme::verify(l)),DestPhase::Done if errs>0=>("CON ERRORES",Theme::warning(l)),DestPhase::Done=>("COMPLETO",Theme::success(l)),DestPhase::Failed=>("ERROR",Theme::error(l)),DestPhase::Cancelled=>("CANCELADO",Theme::muted(l))}}
fn theme_glyph(t:ThemePreference)->&'static str{match t{ThemePreference::System=>"◐",ThemePreference::Light=>"☀",ThemePreference::Dark=>"●"}} fn theme_description(t:ThemePreference)->&'static str{match t{ThemePreference::System=>"Sigue automáticamente el tema de Windows.",ThemePreference::Light=>"Apariencia clara para entornos luminosos.",ThemePreference::Dark=>"Apariencia oscura con menor brillo visual."}}
