impl eframe::App for CopierApp {
 fn update(&mut self,ctx:&egui::Context,_:&mut eframe::Frame){
  if !self.fonts_initialized{setup_fonts(ctx);self.fonts_initialized=true;} self.poll_startup();
  if self.theme_preference==ThemePreference::System&&self.last_theme_check.elapsed()>=THEME_CHECK_INTERVAL{self.use_light_theme=detect_system_theme();self.last_theme_check=Instant::now();} if self.applied_theme!=Some(self.use_light_theme){apply_theme(ctx,self.use_light_theme);self.applied_theme=Some(self.use_light_theme);}
  let snaps=self.job.as_ref().map(|j|j.snapshot()).unwrap_or_default(); let all_terminal=!snaps.is_empty()&&snaps.iter().all(|d|matches!(d.phase,DestPhase::Done|DestPhase::Failed|DestPhase::Cancelled)); let starting=self.starting();let running=self.running_job()&&!all_terminal;let paused=running&&self.job.as_ref().is_some_and(|j|j.is_paused());let verifying=running&&snaps.iter().any(|d|d.phase==DestPhase::Verifying);let busy=starting||running;let now=Instant::now();
  if let Some(until)=self.error_flash_until{if now>=until{self.error_flash_until=None}else{ctx.request_repaint_after(until.saturating_duration_since(now));}} if starting{ctx.request_repaint_after(STARTING_REPAINT)}else if running{ctx.request_repaint_after(if paused{PAUSED_REPAINT}else{RUNNING_REPAINT})}else{ctx.request_repaint_after(THEME_CHECK_INTERVAL)}
  let key=self.paths_key();if key!=self.paths_key||self.last_path_check.elapsed()>=PATH_CHECK_INTERVAL{self.paths_key=key;self.last_path_check=Instant::now();self.path_errors=if busy{vec![]}else{self.validate_paths()};} let path_error_count=self.path_errors.len();let ready=!self.source.trim().is_empty()&&!self.dests.is_empty()&&path_error_count==0;
  egui::TopBottomPanel::top("header_v2").show(ctx,|ui|{ui.add_space(XS);ui.horizontal(|ui|{ui.heading(RichText::new("RepartoCopier").strong());if ui.available_width()>430.0{ui.label(RichText::new("Una carpeta · múltiples destinos").color(Theme::muted(self.use_light_theme)));}ui.with_layout(egui::Layout::right_to_left(egui::Align::Center),|ui|{if ui.add(egui::Button::new(RichText::new("⚙").size(17.0)).frame(false)).on_hover_text("Ajustes").clicked(){self.show_settings=true;}if starting{ui.weak("Validando…");}});});ui.add_space(XS);});
  egui::TopBottomPanel::bottom("footer_v2").show(ctx,|ui|{ui.horizontal(|ui|{let status=if paused{"Copia en pausa"}else if verifying{"Verificando integridad…"}else{&self.status};let color=if self.error_flash_until.is_some(){Theme::error(self.use_light_theme)}else if paused{Theme::warning(self.use_light_theme)}else if verifying{Theme::verify(self.use_light_theme)}else{Theme::muted(self.use_light_theme)};ui.colored_label(color,compact_path(status,72));ui.with_layout(egui::Layout::right_to_left(egui::Align::Center),|ui|{if ui.small_button("Acerca de").clicked(){self.show_credits=true;}});});});
  egui::CentralPanel::default().show(ctx,|ui|{egui::ScrollArea::vertical().auto_shrink([false,false]).show(ui,|ui|{
   ui.add_space(XS);ui.label(RichText::new("ORIGEN").small().strong().color(Theme::muted(self.use_light_theme)));ui.horizontal(|ui|{let button_w=86.0;let field_w=(ui.available_width()-button_w-SM).max(120.0);ui.add_enabled_ui(!busy,|ui|{ui.add_sized([field_w,30.0],egui::TextEdit::singleline(&mut self.source).hint_text("Selecciona la carpeta que quieres copiar"));if ui.add_sized([button_w,30.0],egui::Button::new("Examinar")).clicked(){if let Some(p)=Self::pick_dir(){self.source=p;}}});});
   ui.add_space(MD);ui.horizontal(|ui|{ui.label(RichText::new(format!("DESTINOS  ({})",self.dests.len())).small().strong().color(Theme::muted(self.use_light_theme)));ui.add_enabled_ui(!busy,|ui|{if ui.small_button("+ Agregar").clicked(){if let Some(p)=Self::pick_dir(){if !self.dests.contains(&p){self.dests.push(p)}}}});});
   egui::ScrollArea::vertical().id_salt("destinations_v2").max_height(130.0).show(ui,|ui|{let mut remove=None;for(i,d)in self.dests.iter().enumerate(){card_frame(self.use_light_theme).show(ui,|ui|{ui.horizontal(|ui|{ui.weak(format!("{:02}",i+1));let chars=((ui.available_width()/7.2)as usize).clamp(18,72);ui.label(compact_path(d,chars)).on_hover_text(d);if let Some(p)=snaps.get(i){let(label,color)=phase_label(p.phase,p.files_err,self.use_light_theme,paused);ui.colored_label(color,label);}ui.with_layout(egui::Layout::right_to_left(egui::Align::Center),|ui|{if !busy&&ui.small_button("×").on_hover_text("Quitar destino").clicked(){remove=Some(i);}});});});ui.add_space(XS);}if let Some(i)=remove{self.dests.remove(i);}});
   if path_error_count>0{ui.colored_label(Theme::warning(self.use_light_theme),format!("⚠ {path_error_count} problema(s) de ruta")).on_hover_text(self.path_errors.join("\n"));} ui.separator();
   ui.horizontal_wrapped(|ui|{ui.add_enabled_ui(!busy,|ui|{ui.checkbox(&mut self.skip_same,"Omitir iguales").on_hover_text("Evita copiar de nuevo archivos que ya coinciden.");ui.checkbox(&mut self.keep_going,"Continuar con errores").on_hover_text("Los demás destinos continúan si uno falla.");});ui.with_layout(egui::Layout::right_to_left(egui::Align::Center),|ui|{if running{if let Some(j)=&self.job{if ui.button("Cancelar").clicked(){j.request_cancel();}if ui.button(if paused{"Continuar"}else{"Pausar"}).clicked(){j.set_paused(!paused);}}}else if !starting&&ui.add_enabled(ready,egui::Button::new(RichText::new("Iniciar copia").strong())).clicked(){self.start();}});});
   if starting{ui.add_space(LG);ui.vertical_centered(|ui|{ui.spinner();ui.label(RichText::new("Preparando la copia…").strong());});}
   else if let Some(job)=&self.job{if !snaps.is_empty(){let avg=snaps.iter().map(|p|if p.total==0{if p.phase==DestPhase::Done{1.0}else{0.0}}else{p.written as f64/p.total as f64}).sum::<f64>()/snaps.len()as f64;let total_bps=if paused{0.0}else{snaps.iter().map(|p|shown_bps(p.bps_recent,p.last_tick)).sum()};let eta=if paused{"En pausa".into()}else{let mut ok=true;let mut e=0.0f64;for p in &snaps{let rem=p.total.saturating_sub(p.written);if rem==0||matches!(p.phase,DestPhase::Done|DestPhase::Failed|DestPhase::Cancelled){continue;}if p.bps<=0.0{ok=false;break;}e=e.max(rem as f64/p.bps);}if ok{format_duration(e)}else{"—".into()}};ui.add_space(MD);card_frame(self.use_light_theme).show(ui,|ui|{ui.horizontal_wrapped(|ui|{ui.label(RichText::new("Progreso general").strong());ui.colored_label(if paused{Theme::warning(self.use_light_theme)}else if verifying{Theme::verify(self.use_light_theme)}else{Theme::accent(self.use_light_theme)},if paused{"PAUSADO"}else if verifying{"VERIFICANDO INTEGRIDAD"}else{"COPIANDO"});});ui.add(egui::ProgressBar::new(avg as f32).desired_height(20.0).fill(Theme::accent(self.use_light_theme)).show_percentage());ui.horizontal_wrapped(|ui|{ui.label(RichText::new(format_bps(total_bps)).strong().size(18.0));ui.weak(format!("{} · Tiempo restante {eta}",format_bytes(job.bytes_total.load(Ordering::Relaxed))));});});ui.add_space(SM);for p in &snaps{let frac=if p.total==0{if p.phase==DestPhase::Done{1.0}else{0.0}}else{(p.written as f32/p.total as f32).clamp(0.0,1.0)};let(label,color)=phase_label(p.phase,p.files_err,self.use_light_theme,paused);card_frame(self.use_light_theme).show(ui,|ui|{ui.horizontal_wrapped(|ui|{ui.label(RichText::new(compact_path(&p.label,48)).strong()).on_hover_text(&p.label);ui.colored_label(color,label);});ui.add(egui::ProgressBar::new(frac).desired_height(16.0).fill(Theme::accent(self.use_light_theme)).show_percentage());ui.horizontal_wrapped(|ui|{ui.weak(if paused{"0 B/s".into()}else{format_bps(shown_bps(p.bps_recent,p.last_tick))});ui.weak(format!("{} completados · {} omitidos · {} errores",p.files_done,p.files_skip,p.files_err));});});ui.add_space(XS);}}}
   else{ui.add_space(LG);ui.vertical_centered(|ui|{ui.label(RichText::new("Listo para copiar").size(20.0).strong());ui.label(RichText::new("Selecciona un origen y agrega uno o más destinos.").color(Theme::muted(self.use_light_theme)));});}
  });});
  self.draw_settings(ctx);self.draw_about(ctx);
  if !busy&&all_terminal{let ok=snaps.iter().filter(|d|d.phase==DestPhase::Done&&d.files_err==0).count();let err=snaps.iter().filter(|d|d.phase==DestPhase::Done&&d.files_err>0).count();let fail=snaps.iter().filter(|d|d.phase==DestPhase::Failed).count();let cancel=snaps.iter().filter(|d|d.phase==DestPhase::Cancelled).count();self.status=if cancel>0{format!("Cancelado · {cancel} destino(s)")}else if fail>0||err>0{format!("Finalizado con errores · {} correcto(s) · {} con problemas",ok,fail+err)}else{format!("Completado · {ok}/{} sin errores",snaps.len())};}
 }
}
