pub struct CopierApp {
    source: String,
    dests: Vec<String>,
    skip_same: bool,
    keep_going: bool,
    status: String,
    job: Option<Arc<JobState>>,
    workers: Vec<JoinHandle<()>>,
    startup_rx: Option<mpsc::Receiver<StartResult>>,
    show_credits: bool,
    show_settings: bool,
    error_flash_until: Option<Instant>,
    theme_preference: ThemePreference,
    use_light_theme: bool,
    last_theme_check: Instant,
    applied_theme: Option<bool>,
    fonts_initialized: bool,
    path_errors: Vec<String>,
    last_path_check: Instant,
    paths_key: u64,
}
