from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SHARED = ROOT / 'dotnet/RepartoCopier.Core.Tests/SharedFanoutArchitectureTests.cs'
VERIFY = ROOT / 'dotnet/RepartoCopier.Core.Tests/VerificationArchitectureTests.cs'

shared = SHARED.read_text(encoding='utf-8')
old = '''    [TestMethod]\n    public void VerificationUsesCoordinatedDestinationReadsAgainstCopyTimeCrc()\n    {\n        var engine = File.ReadAllText(Path.Combine(FindRepositoryRoot(), "dotnet", "RepartoCopier.Core", "CopyEngine.cs"));\n        Assert.IsTrue(engine.Contains("Task.WhenAll(reads)", StringComparison.Ordinal));\n        Assert.IsTrue(engine.Contains("FastCrc32C.Compute(target.Buffer!.Memory.Span[..block.Length])", StringComparison.Ordinal));\n        var start = engine.IndexOf("private static async Task VerifyDestinationsAsync", StringComparison.Ordinal);\n        var end = engine.IndexOf("private static async Task<bool[][]> BuildVerifiedSkipMasksAsync", start, StringComparison.Ordinal);\n        Assert.IsTrue(start >= 0 && end > start);\n        var verify = engine[start..end];\n        Assert.IsFalse(verify.Contains("entry.SourcePath", StringComparison.Ordinal), "Verify no debe releer el origen.");\n    }\n'''
new = '''    [TestMethod]\n    public void VerificationUsesStreamingSourceAndDestinationCrcComparison()\n    {\n        var engine = File.ReadAllText(Path.Combine(FindRepositoryRoot(), "dotnet", "RepartoCopier.Core", "CopyEngine.cs"));\n        Assert.IsTrue(engine.Contains("Task.WhenAll(reads)", StringComparison.Ordinal));\n        Assert.IsTrue(engine.Contains("var sourceCrc = FastCrc32C.Compute", StringComparison.Ordinal));\n        Assert.IsTrue(engine.Contains("var destinationCrc = FastCrc32C.Compute", StringComparison.Ordinal));\n        Assert.IsTrue(engine.Contains("destinationCrc != sourceCrc", StringComparison.Ordinal));\n        Assert.IsFalse(engine.Contains("VerificationPlan", StringComparison.Ordinal));\n        Assert.IsFalse(engine.Contains("VerificationBlock", StringComparison.Ordinal));\n    }\n'''
if shared.count(old) != 1:
    raise RuntimeError('old shared verification contract not found exactly once')
SHARED.write_text(shared.replace(old, new, 1), encoding='utf-8')

verify = VERIFY.read_text(encoding='utf-8')
VERIFY.write_text('''using Microsoft.VisualStudio.TestTools.UnitTesting;\n\nnamespace RepartoCopier.Core.Tests;\n\n[TestClass]\npublic sealed class VerificationArchitectureTests\n{\n    [TestMethod]\n    public void VerificationAdvancesSourceAndAllDestinationsTogetherByChunk()\n    {\n        var root = FindRepositoryRoot();\n        var engine = File.ReadAllText(Path.Combine(root, "dotnet", "RepartoCopier.Core", "CopyEngine.cs"));\n        Assert.IsTrue(engine.Contains("ReadVerifyTargetAsync", StringComparison.Ordinal));\n        Assert.IsTrue(engine.Contains("Task.WhenAll(reads)", StringComparison.Ordinal));\n        Assert.IsTrue(engine.Contains("var sourceCrc = FastCrc32C.Compute", StringComparison.Ordinal));\n        Assert.IsTrue(engine.Contains("var destinationCrc = FastCrc32C.Compute", StringComparison.Ordinal));\n        Assert.IsTrue(engine.Contains("destinationCrc != sourceCrc", StringComparison.Ordinal));\n        Assert.IsFalse(File.Exists(Path.Combine(root, "dotnet", "RepartoCopier.Core", "FastVerificationReader.cs")));\n        Assert.IsFalse(File.Exists(Path.Combine(root, "dotnet", "RepartoCopier.Core", "VerificationReadBudget.cs")));\n    }\n\n    [TestMethod]\n    public void VerificationUsesFixedWorkspaceAndNoCopyTimeCrcHistory()\n    {\n        var engine = File.ReadAllText(Path.Combine(FindRepositoryRoot(), "dotnet", "RepartoCopier.Core", "CopyEngine.cs"));\n        var start = engine.IndexOf("private static async Task VerifyDestinationsAsync", StringComparison.Ordinal);\n        var end = engine.IndexOf("private static async Task<bool[][]> BuildVerifiedSkipMasksAsync", start, StringComparison.Ordinal);\n        Assert.IsTrue(start >= 0 && end > start);\n        var verify = engine[start..end];\n        Assert.IsTrue(verify.Contains("entry.SourcePath", StringComparison.Ordinal));\n        Assert.IsTrue(engine.Contains("VerificationWorkspaceBytes = 8 * 1024 * 1024", StringComparison.Ordinal));\n        Assert.IsFalse(engine.Contains("VerificationPlan", StringComparison.Ordinal));\n        Assert.IsFalse(engine.Contains("VerificationBlock", StringComparison.Ordinal));\n        Assert.IsFalse(engine.Contains("VerificationCrc32C", StringComparison.Ordinal));\n        Assert.IsFalse(verify.Contains("PendingRead", StringComparison.Ordinal));\n        Assert.IsFalse(verify.Contains("ExplorationQueueDepth", StringComparison.Ordinal));\n    }\n\n    private static string FindRepositoryRoot()\n    {\n        var current = new DirectoryInfo(AppContext.BaseDirectory);\n        while (current is not null)\n        {\n            if (File.Exists(Path.Combine(current.FullName, "RepartoCopier.sln"))) return current.FullName;\n            current = current.Parent;\n        }\n        throw new AssertFailedException("No se encontró la raíz del repositorio.");\n    }\n}\n''', encoding='utf-8')

print('verification architecture tests aligned')
